import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.scss";
import styles from "../page.module.css";
import SwitcherLanguage from "@/components/SwitcherLanguage";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/TranslationsProvider";
import ReduxProvider from "@/components/ReduxProvider";
import { ConfigProvider } from "antd";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export const metadata: Metadata = {
  title: "SDW Frontend Test",
  description: "Generated by create next app",
};

// export async function generateStaticParams() {
//   return i18nConfig.locales.map((locale) => ({ locale }));
// }

const i18nNamespaces = ["translation"];

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <TranslationsProvider
            locale={locale}
            namespaces={i18nNamespaces}
            resources={resources as Record<string, Record<string, string>>}
          >
            <div className={styles.switcher}>
              <SwitcherLanguage locale={locale} />
            </div>
            {children}
          </TranslationsProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
